server:
  port: 5000
spring:
  application:
    name: ${DB_PROJECT_NAME:revisaop2}


  main:
    allow-bean-definition-overriding: true
  datasource:
    # URL de conexão com o banco de dados
    # Altere 'localhost:3306/nome_do_seu_banco' para os seus dados
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3310}/${DB_NAME:versionamento}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

    # Credenciais de acesso
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}

    # Classe do Driver (Opcional a partir do Spring Boot 2.x, mas boa prática manter)
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Configurações do Pool de Conexões (HikariCP)
    hikari:
      pool-name: HikariPool-MySQL
      maximum-pool-size: 10          # Máximo de conexões ativas simultâneas
      minimum-idle: 5                # Mínimo de conexões ociosas mantidas no pool
      idle-timeout: 600000           # Tempo máximo (ms) que uma conexão pode ficar ociosa (10 min)
      max-lifetime: 1800000          # Vida máxima (ms) de uma conexão no pool (30 min)
      connection-timeout: 30000      # Tempo máximo (ms) de espera por uma conexão (30 seg)

  # Configurações do Hibernate / JPA (Opcional, mas muito comum)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update               # Altere para 'validate' ou 'none' em produção!
    show-sql: true                   # Exibe os comandos SQL no console (bom para desenvolvimento)
    properties:
      hibernate:
        format_sql: true             # Formata o SQL no console para ficar legível

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

cloud:
  aws:
    region:
      static: ${AWS_REGION:us-east-2}
    credentials:
      aws:
        access-key: "SUA_CHAVE_AQUI"
        secret-key: "SEU_SECRET_AQUI"